import React from 'react';
import { Shield } from 'lucide-react'; // Using Lucide for a professional branding icon

/**
 * A visual template for social media images.
 * Designed to be rendered inside the HiddenRenderViewport (1200x630).
 * 
 * @param {Object} props - { title, subtitle, children, disclaimer }
 */
const SocialCardTemplate = ({
    title = "Market Insight",
    subtitle = "Analysis Report",
    children,
    disclaimer = "Generated by BlindMonkey Intelligence Engine. Not financial advice."
}) => {
    return (
        <div className="w-[1200px] h-[630px] bg-slate-900 text-slate-100 flex flex-col p-12 overflow-hidden relative">
            {/* Background Decoration (Subtle Gradient) */}
            <div className="absolute top-0 right-0 w-1/2 h-full bg-gradient-to-l from-blue-500/5 to-transparent pointer-events-none" />

            {/* Header Section */}
            <header className="flex justify-between items-start mb-8 z-10">
                <div className="flex flex-col gap-2">
                    <h1 className="text-4xl font-extrabold tracking-tight text-white m-0">
                        {title}
                    </h1>
                    <p className="text-xl text-slate-400 font-medium m-0">
                        {subtitle}
                    </p>
                </div>

                {/* Branding (Top-Right) */}
                <div className="flex items-center gap-3 bg-slate-800/50 px-5 py-3 rounded-xl border border-slate-700/50">
                    <Shield className="w-8 h-8 text-blue-400" />
                    <span className="text-2xl font-bold tracking-tighter">
                        BlindMonkey<span className="text-blue-400">.io</span>
                    </span>
                </div>
            </header>

            {/* Main Content (Flexible Chart/Metric Area) */}
            <main className="flex-grow flex items-center justify-center bg-slate-800/20 border border-slate-700/30 rounded-2xl overflow-hidden z-10 relative">
                {children ? (
                    <div className="w-full h-full p-6">
                        {children}
                    </div>
                ) : (
                    <div className="text-slate-600 italic">No content provided</div>
                )}
            </main>

            {/* Footer Section */}
            <footer className="mt-8 flex justify-between items-end z-10">
                <p className="text-sm text-slate-500 font-medium m-0 leading-relaxed max-w-[800px]">
                    {disclaimer}
                </p>
                <div className="text-slate-600 text-sm font-bold tracking-widest uppercase">
                    © {new Date().getFullYear()} BlindMonkey
                </div>
            </footer>
        </div>
    );
};

export default SocialCardTemplate;
