groups:
  Index_ETFs:
    - SPY
    - QQQ
    - IWM
    - DIA
  Indexes:
    - ^SPX
    - ^DJI
    - ^IXIC
    - ^RUT
  Sector_ETFs:
    - XLC # Communication Services
    - XLY # Consumer Discretionary
    - XLP # Consumer Staples
    - XLE # Energy
    - XLF # Financials
    - XLV # Health Care
    - XLI # Industrials
    - XLB # Materials
    - XLRE # Real Estate
    - XLK # Technology
    - XLU # Utilities
  Fixed_Income_ETFs:
    - BND
    - AGG
    - BNDX
    - SGOV
    - TLT
    - IEF
    - SHY
    - VCIT
    - VTEB
    - BIL
  Mega_Cap_Tech:
    - AAPL
    - MSFT
    - AMZN
    - GOOGL
    - META
    - TSLA
  Semiconductors:
    - ADI
    - ALAB
    - AMAT
    - AMD
    - ARM
    - ASML
    - AVGO
    - COHR
    - CRDO
    - ENTG
    - GFS
    - INTC
    - KLAC
    - LRCX
    - MCHP
    - MPWR
    - MRVL
    - MTSI
    - MU
    - NVDA
    - NVMI
    - NXPI
    - "ON"
    - QCOM
    - QRVO
    - RMBS
    - SWKS
    - TER
    - TSM
    - TXN
  Energy_Majors:
    - XOM
    - CVX
    - COP
    - APA
    - BKR
    - BP
    - DVN
    - FANG
    - HAL
    - HES
    - MPC
    - OKE
    - OXY
    - PSX
    - SHEL
    - SLB
    - VLO
    - WMB
    - XOM
  Financials_and_Payments:
    - BRK.B
    - JPM
    - V
    - MA
    - BAC
    - WFC
  Health_Care_and_Pharma:
    - LLY
    - JNJ
    - ABBV
    - UNH
    - MRK
    - TMO
  Consumer_Staples_Retail:
    - WMT
    - COST
    - PG
    - PM
    - KO
    - PEP
    - MCD
  Industrials_and_Manufacturing:
    - GE
    - CAT
    - RTX
    - HON
    - DE
  Materials_and_Chemicals:
    - LIN
    - NEM
    - SHW
    - ECL
    - NUE
    - MLM
  Real_Estate_REITs:
    - WELL
    - PLD
    - AMT
    - EQIX
    - SPG
    - O
  Utilities:
    - NEE
    - SO
    - DUK
    - EXC
    - AEP
    - CEG
  Communication_Services_Media:
    - DIS
    - NFLX
    - VZ
    - T
  Other_Large_Cap:
    - HD
    - UBER
    - WMB