tickers:
 - ^GSPC
 - ^DJI
 - ^IXIC
 - ^RUT
 - SPY
 - QQQ
 - IWM
 - DIA
 - XLC
 - XLY
 - XLP
 - XLE
 - XLF
 - XLV
 - XLI
 - XLB
 - XLRE
 - XLK
 - XLU
 - BND
 - AGG
 - BNDX
 - SGOV
 - TLT
 - IEF
 - SHY
 - VCIT
 - VTEB
 - BIL
 - AAPL
 - MSFT
 - NVDA
 - AMZN
 - TSLA
 - GOOGL
 - META
 - XOM
 - CVX
 - BRK.B
 - JPM
 - V
 - MA
 - LLY
 - JNJ
 - ABBV
 - WMT
 - COST
 - PG
 - GE
 - CAT
 - RTX
 - LIN
 - NEM
 - SHW
 - WELL
 - PLD
 - AMT
 - NEE
 - SO
 - CEG
 - DIS
 - HD
 - MCD
 - NFLX
 - VZ
 - T
 - COP
 - WMB
 - BAC
 - WFC
 - UNH
 - MRK
 - TMO
 - PM
 - KO
 - PEP
 - UBER
 - HON
 - DE
 - ECL
 - NUE
 - MLM
 - EQIX
 - SPG
 - O
 - DUK
 - EXC
 - AEP
 - ^SPX
 - ^NDX