tickers:
 - ^GSPC
 - ^DJI
 - ^IXIC
 - ^RUT
 - ^SPX
 - ^NDX
 - SPY
 - QQQ
 - IWM
 - DIA
 - XLC
 - XLY
 - XLP
 - XLE
 - XLF
 - XLV
 - XLI
 - XLB
 - XLRE
 - XLK
 - XLU
 - TLT
 - IEF
 - SHY
 - AAPL
 - MSFT
 - NVDA
 - AMZN
 - TSLA
 - GOOGL
 - META
 - XOM
 - CVX
 - BRK-B
 - JPM
 - V
 - MA
 - LLY
 - JNJ
 - ABBV
 - WMT
 - COST
 - PG
 - GE
 - CAT
 - RTX
 - NEM
 - AMT
 - NEE
 - DIS
 - HD
 - MCD
 - NFLX
 - COP
 - BAC
 - WFC
 - UNH
 - MRK
 - TMO
 - PM
 - KO
 - PEP
 - UBER
 - HON
 - DE
 - NUE