from __future__ import annotations

from app.utils.ui.theme import *  # noqa: F401,F403


# Hidden Markov Model (HMM) page palette
HMM_BULL_COLOR = "#00B050"
HMM_BEAR_COLOR = "#C00000"
HMM_NEUTRAL_COLOR = "#999999"

HMM_PRICE_LINE_COLOR = "#33B5FF"

HMM_HEATMAP_LOW_COLOR = "#E0E0E0"
HMM_HEATMAP_MID_COLOR = "#F2C94C"
HMM_HEATMAP_HIGH_COLOR = "#008F39"

HMM_STATE_COLORS = {
	"Bull": HMM_BULL_COLOR,
	"Bear": HMM_BEAR_COLOR,
	"Neutral": HMM_NEUTRAL_COLOR,
}

HMM_HEATMAP_COLORSCALE = [
	[0.0, HMM_HEATMAP_LOW_COLOR],
	[0.5, HMM_HEATMAP_MID_COLOR],
	[1.0, HMM_HEATMAP_HIGH_COLOR],
]

